name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache all the things
        uses: ./.github/actions/cache-all-the-things
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Check types with mypy
        run: hatch run types:check
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache all the things
        uses: ./.github/actions/cache-all-the-things
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run tests
        run: hatch test
